// Code generated by anathema, DO NOT EDIT.
package subcommands

import (
	"github.com/bobappleyard/anathema/component/registry"
	"reflect"
)

func init () {
	registry.RegisterType(reflect.TypeOf(new(applicationCommand)).Elem())
	registry.RegisterType(reflect.TypeOf(new(packageCommand)).Elem())
}
