// Code generated by anathema, DO NOT EDIT.
package util

import (
	"github.com/bobappleyard/anathema/component/registry"
	"reflect"
)

func init () {
	registry.RegisterType(reflect.TypeOf(new(envField)).Elem())
	registry.RegisterType(reflect.TypeOf(new(fileSystem)).Elem())
	registry.RegisterType(reflect.TypeOf(new(generator)).Elem())
	registry.RegisterType(reflect.TypeOf(new(moduleAnalyzer)).Elem())
	registry.RegisterType(reflect.TypeOf(new(packageAnalyzer)).Elem())
}
