// Code generated by anathema, DO NOT EDIT.
package a

import (
	"github.com/bobappleyard/anathema/component/registry"
	"reflect"
)

func init () {
	registry.RegisterType(reflect.TypeOf(new(Provider)).Elem())
	registry.RegisterType(reflect.TypeOf(new(Service)).Elem())
}
