// Code generated by anathema, DO NOT EDIT.
package resource

import (
	"github.com/bobappleyard/anathema/component/registry"
	"reflect"
)

func init () {
	registry.RegisterType(reflect.TypeOf(new(get)).Elem())
	registry.RegisterType(reflect.TypeOf(new(head)).Elem())
	registry.RegisterType(reflect.TypeOf(new(intEncoding)).Elem())
	registry.RegisterType(reflect.TypeOf(new(methodEncoding)).Elem())
	registry.RegisterType(reflect.TypeOf(new(path)).Elem())
	registry.RegisterType(reflect.TypeOf(new(stringEncoding)).Elem())
	registry.RegisterType(reflect.TypeOf(new(tagRule)).Elem())
}
