// Code generated by anathema, DO NOT EDIT.
package main

import (
	"github.com/bobappleyard/anathema/component/registry"
	"reflect"
)

func init () {
	registry.RegisterType(reflect.TypeOf(new(application)).Elem())
	registry.RegisterType(reflect.TypeOf(new(repository)).Elem())
	registry.RegisterType(reflect.TypeOf(new(userResource)).Elem())
}
