// Code generated by anathema, DO NOT EDIT.
package main

import (
	_ "github.com/bobappleyard/anathema/component/a"
	_ "github.com/bobappleyard/anathema/server/a"
	_ "github.com/bobappleyard/anathema/cmd/anathema/internal/subcommands"
	_ "github.com/bobappleyard/anathema/cmd/anathema/internal/subcommands/services"
	_ "github.com/bobappleyard/anathema/server/resource"
	_ "github.com/bobappleyard/anathema/cmd/anathema/internal/util"
)
