// Code generated by anathema, DO NOT EDIT.
package services

import (
	"github.com/bobappleyard/anathema/component/registry"
	"reflect"
)

func init () {
	registry.RegisterType(reflect.TypeOf(new(componentFileCompiler)).Elem())
	registry.RegisterType(reflect.TypeOf(new(importFileCompiler)).Elem())
}
